#ifndef SG_MAP
#define SG_MAP

#define sg_current_map (*(u16*)0x800E7A72)
#define sg_next_map (*(u16*)0x800E7B3E)
#define sg_previous_map (*(u16*)0x800E7B20)
enum {
    MAP_START = 0x00,
    MAP_SEWER_ENTRANCE = 0x24,
    MAP_SEWER_SECOND_CAVE_ENTRANCE = 0x25,
    MAP_SEWER_FIRST_CAVE_ENTRANCE = 0x26,
    MAP_SEWER_CAVE_WATER = 0x27,
    MAP_SEWER_TO_CHAPEL = 0x28,
    MAP_SEWER_TO_STARTING_TOWER = 0x31,
    MAP_TOWER1_HALL = 0x33,
    MAP_TOWER1_STOREROOM = 0x30,
    MAP_TOWER1_BEDROOM = 0x2F,
    MAP_TOWER1_SMALL_HALL = 0x32,
    MAP_TOWER1_UPSTAIRS = 0x35,
    MAP_TOWER1_ENTRANCE = 0x36,
    MAP_TOWER1_2FLR = 0x37,
    MAP_TOWER1_STUDENT_STUDY = 0x38,
    MAP_TOWER1_3FLR = 0x3B,
    MAP_TOWER1_3OFFICE = 0x3C, //Fairy, Elf, Human
    MAP_TOWER1_3CLASS2 = 0x3A,
    MAP_TOWER1_3CLASS1 = 0x39,
    MAP_TOWER1_4FLR = 0x3F,
    MAP_TOWER1_4COT1 = 0x3E,
    MAP_TOWER1_4COT2 = 0x3D,
    MAP_TOWER1_WINDOW = 0x40,
    MAP_OUTSIDE_HOLE = 0x41,
    MAP_CEMETERY = 0x0A,
    MAP_CHAPEL_COURTYARD = 0x0B,
    MAP_CHAPEL = 0x0E,
    MAP_CHAPEL_BASEMENT = 0x0D,
    MAP_CHAPEL_COFFINS = 0x0C,
    MAP_CHAPEL_ROOF = 0x0F,
    MAP_LAKMIR_TOWER_WINDOW_ENTRANCE = 0x4E,
    MAP_LAKMIR_TOWER_2FLR_HALL = 0x50,
    MAP_LAKMIR_TOWER_KITCHEN = 0x4F,
    MAP_LAKMIR_TOWER_DINING_ROOM = 0x4C,
    MAP_LAKMIR_TOWER_EMPTY_ROOM = 0x4D,
    MAP_LAKMIR_TOWER_DOWNSTAIRS = 0x4A,
    MAP_LAKMIR_GRAND_HALL = 0x47,
    MAP_LAKMIR_1FLR_HALL = 0x4B,
    MAP_LAKMIR_LEFT_OFFICE = 0x49,
    MAP_LAKMIR_RIGHT_OFFICE = 0x48,
    MAP_LAKMIR_GFLR_HALL = 0x42,
    MAP_LAKMIR_PIPE_HALL = 0x43,
    MAP_LAKMIR_PIPE_ROOM = 0x44,
    MAP_LAKMIR_STATUE_ROOM_1 = 0x51,
    MAP_LAKMIR_STATUE_ROOM_2 = 0x53, // 2 statues looking left and right
    MAP_LAKMIR_STATUE_ROOM_3 = 0x52, // 2 statues looking each other
    MAP_LAKMIR_STATUE_ROOM_4 = 0x55, // 4 statues
    MAP_LAKMIR_STATUE_ROOM_5 = 0x54, // 4 statues
    MAP_LAKMIR_2DOOR_ROOM = 0x46,
    MAP_LAKMIR_TOME_ROOM = 0x45,
    MAP_LAKMIR_AFTER_PUZZLE_HALL = 0x56,
    MAP_LAKMIR_METAL_MACHINE = 0x57,
    MAP_LAKMIR_BEDROOM = 0x58,
    MAP_LAKMIR_RING_ROOM = 0x59,
    MAP_TOWN = 0x10,
    MAP_INN = 0x11,
    MAP_SHOP = 0x13,
    MAP_BROKEN_SIDE_OF_TOWN = 0x1E,
    MAP_TRIAL_TOWER_DEATH_MAZE = 0x63,
    MAP_TRIAL_TOWER_BEFORE_MAZE = 0x65,
    MAP_RUINS = 0x2C,
    MAP_END = 0x2E
};
#endif